site_name: Osiris Documentation
site_url: https://example.com
docs_dir: docs
nav:
  - Home: index.html
  - API: openapi.md
  - Day 2 Ops: DAY2_OPERATIONS.md
  - Troubleshooting: ADVANCED_TROUBLESHOOTING.md
plugins:
  - search
  - swagger-ui-tag
theme:
  name: material
