[build-system]
requires = ["setuptools>=68", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "osiris"
version = "0.0.0"

[tool.setuptools.packages.find]
include = ["osiris*", "llm_sidecar*", "osiris_policy*"]

[tool.black]
line-length = 88
target-version = ["py310"]
required-version = "24.2.0"

[tool.ruff]
target-version = "py310"
line-length = 88
required-version = "0.4.4"
exclude = ["osiris/scripts/*"]

[tool.ruff.lint]
select = ["E9"]

[tool.semantic_release]
version_variable = "pyproject.toml:version"
tag_format = "v{version}"

[tool.pytest.ini_options]
asyncio_default_fixture_loop_scope = "function"
