[build-system]
requires = ["setuptools>=68", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "osiris"
version = "0.0.0"

[tool.setuptools.packages.find]
include = ["osiris*", "llm_sidecar*", "osiris_policy*"]

[tool.black]
line-length = 88
target-version = ["py310"]
required-version = "24.4.2"

[tool.ruff]
target-version = "py310"
line-length = 88
required-version = "0.4.4"
select = ["E9"]
