apiVersion: apps/v1
kind: Deployment
metadata:
  name: azr-planner
spec:
  template:
    spec:
      containers:
        - name: azr-planner
          image: your-registry/82edge_osiris:latest
          env:
            - name: ALPHA_TASKS_PER_UNIT
              value: "{{ .Values.azrPlanner.alphaTasksPerUnit | quote }}"
            - name: BETA_TASKS_PER_UNIT
              value: "{{ .Values.azrPlanner.betaTasksPerUnit | quote }}"
            - name: ALPHA_IN_USE
              value: "{{ .Values.azrPlanner.alphaInUse | default \"0\" | quote }}"
            - name: BETA_IN_USE
              value: "{{ .Values.azrPlanner.betaInUse | default \"0\" | quote }}"
          ports:
            - containerPort: 8080
