{{- if .Values.azrPlanner.enabled -}}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "osiris.fullname" . }}-azr-planner
  labels:
    {{- include "osiris.labels" . | nindent 4 }}
    app.kubernetes.io/component: azr-planner
spec:
  type: {{ .Values.azrPlanner.service.type }}
  ports:
    - port: {{ .Values.azrPlanner.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "osiris.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: azr-planner
{{- end }}
