{{- if .Values.observability.grafana.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "osiris.fullname" . }}-grafana-datasource
  labels:
    {{- include "osiris.labels" . | nindent 4 }}
    app.kubernetes.io/component: grafana
  annotations:
    grafana_datasource: "1"
data:
  datasources.yaml: |-
    apiVersion: 1
    datasources:
      - name: Prometheus
        type: prometheus
        access: proxy
        url: {{ .Values.observability.grafana.prometheus.url }}
        isDefault: true
{{- end }}
