apiVersion: v1
kind: Service
metadata:
  name: {{ include "osiris.fullname" . }}-llm-sidecar
  labels:
    {{- include "osiris.labels" . | nindent 4 }}
    app.kubernetes.io/component: llm-sidecar
spec:
  type: {{ .Values.llmSidecar.service.type }}
  ports:
    - port: {{ .Values.llmSidecar.service.port }}
      targetPort: http-llm
      protocol: TCP
      name: http-llm
  selector:
    {{- include "osiris.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: llm-sidecar
