apiVersion: v1
kind: Service
metadata:
  name: {{ include "osiris.fullname" . }}-orchestrator
  labels:
    {{- include "osiris.labels" . | nindent 4 }}
    app.kubernetes.io/component: orchestrator
spec:
  type: {{ .Values.orchestrator.service.type }}
  ports:
    - port: {{ .Values.orchestrator.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "osiris.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: orchestrator
