{{- if .Values.orchestrator.config }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "osiris.fullname" . }}-orchestrator-config
  labels:
    {{- include "osiris.labels" . | nindent 4 }}
    app.kubernetes.io/component: orchestrator
data:
  {{- range $key, $value := .Values.orchestrator.config }}
  {{- if and $.Values.otelCollectorSidecar.enabled (eq $key "OTEL_EXPORTER_OTLP_ENDPOINT") }}
  {{ $key }}: {{ $.Values.otelCollectorSidecar.endpoint | quote }}
  {{- else }}
  {{ $key }}: {{ $value | quote }}
  {{- end }}
  {{- end }}
{{- end }}
