services:
  lancedb:
    image: lancedb/lancedb-server:latest   # CPU-only build
    container_name: lancedb
    ports:
      - "8100:8100"        # gRPC
      - "8101:8101"        # REST / HTTP
    volumes:
      - ./lancedb_data:/data

  redis:
    image: redis:7-alpine
    container_name: redis
    ports:
      - "6379:6379"
