from typing import Any, Protocol, Iterable, Self

class LanceTable(Protocol):
    def to_arrow(self) -> Any: ...
    def add(self, rows: Iterable[dict[str, Any]]) -> None: ...

class DBConnection(Protocol):
    def open_table(self, name: str) -> LanceTable: ...
    def table(self, name: str) -> LanceTable: ...

def connect(uri: str) -> DBConnection: ...
