# +++ Create this new file +++
from typing import Any, Iterable, Protocol, Type

class LanceTable(Protocol):
    def to_arrow(self) -> Any:...

class DBConnection(Protocol):
    def open_table(self, name: str) -> LanceTable:...
    def table(self, name: str) -> LanceTable:...

def connect(uri: str) -> DBConnection:...

class pydantic:
    class LanceModel:...
    def Vector(dim: int) -> Any:...
