replicaCount: 1

image:
  repository: ghcr.io/your-user/dgm-kernel
  pullPolicy: IfNotPresent
  tag: ""

service:
  type: ClusterIP
  port: 8000
  targetPort: 8000

monitoring:
  enabled: false
  interval: 30s
