replicaCount: 1

image:
  repository: ghcr.io/your-user/dgm-kernel # Repository will be updated by CI
  pullPolicy: IfNotPresent
  # tag is purposefully omitted here. Helm will default to Chart.appVersion if not set.
  # Example: --set image.tag="your-dynamic-tag"
  tag: ""

service:
  type: ClusterIP
  port: 8000
  targetPort: 8000

monitoring:
  enabled: false
  interval: 30s
