name: Release Docker Images

on:
  push:
    tags:
      - 'v*.*.*'
  workflow_dispatch:
    inputs:
      multi:
        description: 'Build multi-platform images (linux/amd64, linux/arm64)'
        required: false
        default: 'false'
        type: boolean

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: write
    env:
      TAG: ${{ github.ref_name }}
      MULTI: ${{ inputs.multi || 'false' }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install semantic-release
        run: pip install python-semantic-release

      - name: Determine next version
        if: github.event_name == 'workflow_dispatch'
        id: semver
        run: |
          NEXT_TAG=$(semantic-release version --print-tag --no-commit --no-tag --no-changelog --no-push)
          echo "TAG=$NEXT_TAG" >> "$GITHUB_ENV"
          echo "tag=$NEXT_TAG" >> "$GITHUB_OUTPUT"

      - name: Create Git tag
        if: github.event_name == 'workflow_dispatch'
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git tag "$TAG"
          git push origin "$TAG"

      - name: Determine platforms
        id: platforms
        run: |
          if [ "${{ env.MULTI }}" = "true" ]; then
            echo "PLATFORMS=linux/amd64,linux/arm64" >> "$GITHUB_OUTPUT"
          else
            echo "PLATFORMS=" >> "$GITHUB_OUTPUT"
          fi

      - name: Build and push llm-sidecar
        uses: ./.github/actions/docker_build
        with:
          image_name: ghcr.io/${{ github.repository_owner }}/llm-sidecar
          image_tag: ${{ env.TAG }}
          dockerfile: docker/Dockerfile
          context: docker
          push_image: true
          registry_user: ${{ github.actor }}
          registry_password: ${{ secrets.GITHUB_TOKEN }}
          platforms: ${{ steps.platforms.outputs.PLATFORMS }}

      - name: Build and push azr_planner
        uses: ./.github/actions/docker_build
        with:
          image_name: ghcr.io/${{ github.repository_owner }}/azr_planner
          image_tag: ${{ env.TAG }}
          dockerfile: services/azr_planner/Dockerfile
          context: .
          push_image: true
          registry_user: ${{ github.actor }}
          registry_password: ${{ secrets.GITHUB_TOKEN }}
          platforms: ${{ steps.platforms.outputs.PLATFORMS }}

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ env.TAG }}
          name: ${{ env.TAG }}
          generate_release_notes: true

  deploy-docs:
    needs: build-and-push
    uses: ./.github/workflows/docs.yml
    secrets: inherit

